//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certified_Label.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int LetterID { get; set; }
        public string DepartmentName { get; set; }
        public string CaseNumber { get; set; }
        public string Subject { get; set; }
        public string Date { get; set; }
        public string Contact { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Department Department { get; set; }
    }
}
